name: Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Build Release
        run: cargo build --release

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/whatcolor.exe
            install.ps1
          name: Build ${{ github.run_number }}
          tag_name: build-${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
